# Generated by Django 3.2 on 2021-06-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('image_1', models.ImageField(null=True, upload_to='images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('section_type', models.CharField(choices=[('image-block', 'Image Block'), ('compare-block', 'Compare Block')], max_length=50, null=True, verbose_name='Type')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
